 steps:
# - name: maven:3-jdk-8
 #  entrypoint: mvn
 #  args: ['test']
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'gcr.io/ordinal-gear-284103/sample-p1', '--build-arg=JAR_FILE=target/spring-boot-starter-parent-*.jar', '.']
 images: ['gcr.io/ordinal-gear-284103/sample-p1']
   
   
   
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'gcr.io/ordinal-gear-284103/sample-p1', '.' ]
